# Generated by Django 5.0.6 on 2024-06-07 21:38

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Masal Hiyenin başlığını girin.", max_length=255
                    ),
                ),
                ("hiddenTitle", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Şiirin URL'de görünecek kısmını girin.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "h1",
                    models.CharField(
                        blank=True,
                        help_text="İçeriğin H1 Seo uyumlu girilmesi Lazım.",
                        max_length=255,
                    ),
                ),
                ("hiddenH1", models.TextField(blank=True, null=True)),
                ("content", tinymce.models.HTMLField()),
                (
                    "yazar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Melih ÖZKAŞ", "Melih ÖZKAŞ"),
                            ("Hava ÖZKAŞ", "Hava ÖZKAŞ"),
                            ("Ebru GÜNEŞ", "Ebru GÜNEŞ"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("ozet", models.TextField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True)),
                ("youtube2", models.URLField(blank=True)),
                ("youtube3", models.URLField(blank=True)),
                ("twitterwidget", models.TextField(blank=True, null=True)),
                ("twitterwidget2", models.TextField(blank=True, null=True)),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        verbose_name="Meta Açıklama",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        verbose_name="Anahtar Kelimeler",
                    ),
                ),
                ("hiddenKeys", models.TextField(blank=True, null=True)),
                (
                    "yayin_tarihi",
                    models.DateTimeField(
                        blank=True,
                        help_text="Postanın yayınlanacağı tarih ve saat",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Taslak", "Taslak"),
                            ("Hazir", "Hazir"),
                            ("Yayinda", "Yayinda"),
                            ("oto", "oto"),
                            ("manuel", "manuel"),
                        ],
                        default="Taslak",
                        help_text="Şiirin durumunu seçin.",
                        max_length=10,
                    ),
                ),
                (
                    "gonder",
                    models.BooleanField(
                        default=False, help_text="Whatsapp ve Telegramda paylaş"
                    ),
                ),
                (
                    "SosyalDik",
                    models.CharField(
                        choices=[
                            ("Bilgi Bekleniyor", "Bilgi Bekleniyor"),
                            ("Yapma", "Yapma"),
                            ("Hazirla", "Hazirla"),
                            ("Tamamlandi", "Tamamlandi"),
                        ],
                        default="Bilgi Bekleniyor",
                        max_length=255,
                    ),
                ),
                (
                    "SosyalKare",
                    models.CharField(
                        choices=[
                            ("Bilgi Bekleniyor", "Bilgi Bekleniyor"),
                            ("Yapma", "Yapma"),
                            ("Hazirla", "Hazirla"),
                            ("Tamamlandi", "Tamamlandi"),
                        ],
                        default="Bilgi Bekleniyor",
                        max_length=255,
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=False,
                        help_text="Şiirin aktif olup olmadığını belirtin.",
                    ),
                ),
                (
                    "indexing",
                    models.BooleanField(default=False, help_text="Indexlensin mi?"),
                ),
                (
                    "banner",
                    models.BooleanField(
                        default=False,
                        help_text="Ana Sayfadaki büyük resim alanında ögrünür",
                    ),
                ),
                (
                    "editor",
                    models.BooleanField(
                        default=False, help_text="Ana sayfada küçük resimlerde görünür."
                    ),
                ),
                (
                    "facebook",
                    models.BooleanField(
                        default=True, help_text="Facebook da Paylaşılsın mı ?"
                    ),
                ),
                (
                    "twitter",
                    models.BooleanField(
                        default=True, help_text="twitter da Paylaşılsın mı ?"
                    ),
                ),
                (
                    "pinterest",
                    models.BooleanField(
                        default=True, help_text="twitter da Paylaşılsın mı ?"
                    ),
                ),
                ("okunma_sayisi", models.PositiveBigIntegerField(default=0)),
                ("Kaynak_Linki", models.URLField(blank=True, null=True)),
                ("Kaynak_Follow", models.TextField(blank=True, null=True)),
                ("Kaynak_NoFollow", models.TextField(blank=True, null=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Post",},
        ),
    ]
