# Generated by Django 5.0.6 on 2024-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="hiddenH1",),
        migrations.AddField(
            model_name="post",
            name="resim",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="resim2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="resim3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
