# Generated by Django 5.0.6 on 2024-06-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0002_remove_post_hiddenh1_post_resim_post_resim2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="SosyalDik",),
        migrations.AddField(
            model_name="post",
            name="Post_Turu",
            field=models.CharField(
                choices=[("isim", "isim"), ("post", "post")],
                default="isim",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="Post_type",
            field=models.CharField(
                choices=[
                    ("Article", "Article"),
                    ("NewsArticle", "NewsArticle"),
                    ("BlogPosting", "BlogPosting"),
                ],
                default="Article",
                max_length=255,
                null=True,
            ),
        ),
    ]
