# Generated by Django 5.0.6 on 2024-06-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0004_remove_post_content_post_icerik1_post_icerik2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="hiddenTitle",),
        migrations.AlterField(
            model_name="post",
            name="Post_Turu",
            field=models.CharField(
                choices=[("isim", "isim"), ("blog", "blog")],
                default="isim",
                max_length=255,
                null=True,
            ),
        ),
    ]
