# Generated by Django 5.0.6 on 2024-06-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0005_remove_post_hiddentitle_alter_post_post_turu"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="hiddenKeys",),
    ]
