# Generated by Django 5.0.6 on 2024-06-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0006_remove_post_hiddenkeys"),
    ]

    operations = [
        migrations.CreateModel(
            name="allname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Masal Hiyenin başlığını girin.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "Post_Turu",
                    models.CharField(
                        choices=[
                            ("Beklemede", "Beklemede"),
                            ("Yolda", "Yolda"),
                            ("Tamamlandı", "Tamamlandı"),
                        ],
                        default="Beklemede",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Tüm isimler",},
        ),
    ]
