# Generated by Django 5.0.6 on 2024-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0008_rename_post_turu_allname_durum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="isim",
            field=models.CharField(
                blank=True,
                help_text="İçeriğin H1 Seo uyumlu girilmesi Lazım.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="allname",
            name="Cinsiyet",
            field=models.CharField(
                choices=[
                    ("Kız", "Kız"),
                    ("Erkek", "Erkek"),
                    ("Unisex", "Unisex"),
                    ("B", "B"),
                ],
                default="B",
                max_length=255,
                null=True,
            ),
        ),
    ]
