# Generated by Django 5.0.6 on 2024-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0009_post_isim_alter_allname_cinsiyet"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Caiz",
            field=models.BooleanField(
                default=False, help_text="Şiirin aktif olup olmadığını belirtin."
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="Kuran",
            field=models.BooleanField(
                default=False, help_text="Şiirin aktif olup olmadığını belirtin."
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="kisaanlam",
            field=models.TextField(blank=True, null=True),
        ),
    ]
