# Generated by Django 5.0.6 on 2024-06-15 18:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0010_post_caiz_post_kuran_post_kisaanlam"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Cinsiyet",
            field=models.CharField(
                choices=[
                    ("Kız", "Kız"),
                    ("Erkek", "Erkek"),
                    ("Unisex", "Unisex"),
                    ("Bekleniyor", "Bekleniyor"),
                ],
                default="Bekleniyor",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="icerik1",
            field=tinymce.models.HTMLField(
                blank=True, help_text="ismin uzun anlamı kökeni vs...", null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="icerik2",
            field=tinymce.models.HTMLField(
                blank=True, help_text="ismin ismin kişilik özellikleri", null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="isim",
            field=models.CharField(
                blank=True,
                help_text="Sadece ismin kendisi küçük harflerle",
                max_length=255,
            ),
        ),
    ]
