# Generated by Django 5.0.6 on 2024-06-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "isimler",
            "0011_post_cinsiyet_alter_post_icerik1_alter_post_icerik2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Benzerisimler",
            field=models.TextField(blank=True, null=True),
        ),
    ]
