# Generated by Django 5.0.6 on 2024-06-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0012_post_benzerisimler"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("H1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("short_title", models.CharField(blank=True, max_length=255)),
                ("Aktif", models.BooleanField(default=False)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Post Kategori",},
        ),

    ]
