# Generated by Django 5.0.6 on 2024-06-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0013_postkategori_alter_post_post_turu"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="Post_Turu",),
    ]
