# Generated by Django 5.0.6 on 2024-06-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0015_post_post_turu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postkategori", old_name="Aktif", new_name="aktif",
        ),
    ]
