# Generated by Django 5.0.6 on 2024-06-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0016_rename_aktif_postkategori_aktif"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="Cinsiyet",),
    ]
