# Generated by Django 5.0.6 on 2024-06-21 20:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0017_remove_post_cinsiyet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postkategori", old_name="H1", new_name="h1",
        ),
        migrations.AlterField(
            model_name="post",
            name="icerik2",
            field=tinymce.models.HTMLField(
                blank=True, help_text="ismin kişilik özellikleri", null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="icerik3",
            field=tinymce.models.HTMLField(
                blank=True, help_text="isminde ki ünlü isimler!", null=True
            ),
        ),
    ]
