# Generated by Django 5.0.6 on 2024-06-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0018_rename_h1_postkategori_h1_alter_post_icerik2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="meta_description", new_name="description",
        ),
    ]
