# Generated by Django 5.0.6 on 2024-06-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0019_rename_meta_description_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="postkategori",
            name="resim",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
