# Generated by Django 5.0.6 on 2024-06-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isimler", "0020_postkategori_resim"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Trend",
            field=models.BooleanField(
                default=False, help_text="Ana Sayfada Popülerde Çıkar!"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="indexing",
            field=models.BooleanField(default=True, help_text="Indexlensin mi?"),
        ),
    ]
